### ISSUE TITLE
Doesn't work with node v4.2.1

### ISSUE THREAD

**Issue by jdfreder** [arqex/amdrequire#2]
Looks like it's expecting request to be a string, but it's not.

```
TypeError request.substring is not a function TypeError: request.substring is not a function
    at Function.Module._resolveLookupPaths (module.js:214:23)
    at Function.Module._resolveFilename (module.js:327:31)
    at Function.Module._load (module.js:287:25)
    at noderequire (/home/jon/ipython/ipywidgets/node_modules/amdrequire/amdrequire.js:10:17)
    at /home/jon/ipython/ipywidgets/node_modules/amdrequire/amdrequire.js:54:5
    at Array.forEach (native)
    at amdrequire (/home/jon/ipython/ipywidgets/node_modules/amdrequire/amdrequire.js:37:8)
    at define (/home/jon/ipython/ipywidgets/node_modules/amdrequire/amdrequire.js:115:10)
    at Object.<anonymous> (/home/jon/ipython/ipywidgets/examples/development/embeding/node_modules/ipywidgets/ipywidgets/static/widgets/js/manager-base.js:4:1)
    at Module._compile (module.js:435:26) [TypeError: request.substring is not a function]
```

**Comment by Saltallica** [comment]
Same issue here

**Comment by Muzietto** [comment]
Same in my case. That's what you call a properly maintained npm package. Let's move over...
